const ITEMS_QUERY_KEY = 'ITEMS_QUERY_KEY'
const SIGNUP_QUERY_KEY = 'SIGNUP_QUERY_KEY'
const SIGNIN_QUERY_KEY = 'SIGNIN_QUERY_KEY'
const USER_INFO_QUERY_KEY = 'USER_INFO_QUERY_KEY'

export {
  ITEMS_QUERY_KEY,
  SIGNIN_QUERY_KEY,
  SIGNUP_QUERY_KEY,
  USER_INFO_QUERY_KEY,
}
