const ITEMS_QUERY_KEY = 'ITEMS_QUERY_KEY'
const USER_INFO_QUERY_KEY = 'USER_INFO_QUERY_KEY'
const ITEM_QUERY_KEY = 'ITEM_QUERY_KEY_'
const ITEM_DETAIL_QUERY_KEY = 'ITEM_DETAIL_QUERY_KEY'
const ITEM_REVIEWS_QUERY_KEY = 'ITEM_REVIEWS_QUERY_KEY_'

export {
  ITEMS_QUERY_KEY,
  USER_INFO_QUERY_KEY,
  ITEM_QUERY_KEY,
  ITEM_DETAIL_QUERY_KEY,
  ITEM_REVIEWS_QUERY_KEY,
}
