const USER_TOKEN_STORAGE_KEY = 'USER_TOKEN_STORAGE_KEY'
const USER_GROUP_STORAGE_KEY = 'USER_GROUP_STORAGE_KEY'
const USER_CART_STORAGE_KEY = 'USER_CART_STORAGE_KEY'

export {
  USER_GROUP_STORAGE_KEY,
  USER_TOKEN_STORAGE_KEY,
  USER_CART_STORAGE_KEY,
}
